connect-foundation/2019-15

.travis.yml

- master 브랜치일 때 test:prod으로 테스트
- develop 브랜치일 때 test:dev으로 테스트

travis 구동 시 test command 브랜치 별로 구분

---

.travis.yml
back/Dockerfile.dev
front/Dockerfile.dev
front/conf/conf.d/default.conf

- Dockerfile.dev: development용 도커파일
- Dockerfile: production용 도커파일

환경에 따라 Dockerfile 구분

---

.travis.yml

- .env가 없는 디렉토리에서 .env 수정하는 에러 수정

Travis 에러 수정

---

back/middleware/authenticate.js
front/src/components/LoginSection/LoginFacebook/LoginFacebook.js
front/src/components/LoginSection/LoginGoogle/LoginGoogle.js

Feature login logic2

---

README.md

master: docs: fix README.md

---

back/package-lock.json

실수로 package.json만 올렸어서 추가로 올림..

env: add grapql-tag in package-lock.json

---

back/middleware/authenticate.js
back/router/auth/auth.js
back/router/auth/google.js
back/util/getCookieOption.js
back/util/signJWT.js

Feature cookie

---

back/socket/Room.js
back/socket/index.js
front/.gitignore
front/src/components/GameInfo/GameInfo.js
front/src/components/GameInfo/GameInfo.style.js
front/src/components/GameLoading/GameLoading.style.js
front/src/components/NavigationBar/ButtonContainer/ButtonContainer.js
front/src/components/NavigationBar/ButtonContainer/ButtonContainer.style.js
front/src/components/RoomSelectSection/PublicRoom/PublicRoom.js
front/src/components/Userlist/User/User.style.js
front/src/components/Userlist/Userlist.style.js
front/src/logics/socketLogic/index.js

게임 나가기 기능 구현
클라이언트에서 나가기 요청 보내고
서버에서는 그에 대한 핸들링과
다른 유저에게 새로운 유저리스트 전송

Feature game exit

---

front/src/components/Ranking/RankingAll/RankingAll.js
front/src/components/Ranking/RankingFriends/RankingFriends.js
front/src/components/globalComponents/InfinityScroll/InfinityScroll.js
front/src/components/globalComponents/InfinityScroll/InfinityScroll.style.js
front/src/queries/ranking.js

- 랭킹이나 알람 등에 사용할 InfinityScroll 컴포넌트 구현

Feature infinity scroll

---

back/socket/index.js
front/src/components/CanvasSection/WordChoice/WordChoice.js
front/src/components/RoomSelectSection/PublicRoom/PublicRoom.js
front/src/logics/socketLogic/index.js

형준오빠랑 같은쪽 구현하는게 있어서
호다닥 올려봅니당
정답을 서버에서 가지고있는 부분이에엽

Feature chatting

---

front/src/components/CanvasSection/CanvasSection.js
front/src/components/Timer/Timer.js

ref로 Timer의 함수를 직접 호출하는 대신, props를 이용하여 타이머를 조절하도록 수정함.
Signed-off-by: Einere <kjwsx23@gmail.com>

fix(Timer): use props instead of useRef

---

back/socket/online/requestFriend.js
front/src/Router.js
front/src/components/FriendsSection/FriendsList/FriendsSetModal/FriendsSetModal.js
front/src/components/MyInfoSection/ChangeMyInfo/NicknameChangeContainer/NicknameChangeBtn.js
front/src/components/NavigationBar/ButtonContainer/ButtonContainer.js
front/src/logics/socketLogic/online.js
front/src/pages/Main/Main.js

- useReducer에서 state변경 함수의 이름을 ~dispatch로 변경
- emit 함수 또한 socket file로 이동

알람 기능 리팩토링

---

front/src/components/CanvasSection/CanvasSection.js
front/src/components/CanvasSection/WordChoice/WordChoice.js
front/src/components/CanvasSection/WordPreview/WordPreview.js
front/src/components/Timer/Timer.js

Feature question word

---

front/src/logics/auth/checkAuth.js
front/src/logics/auth/checkAutoLogIn.js

해시 라우터로 바꿨는데 리디렉트는 full uri라서 자동 로그인에 성공해도 홈 페이지로 리디렉트 되는 현상이 발생.
해당 버그를 잡기 위해, 리디렉트 경로를 수정함.
Signed-off-by: Einere <kjwsx23@gmail.com>

fix(redirect): modify full uri to hash uri

---

front/src/components/FriendsSection/FriendsList/FriendsSetModal/FriendsSetModal.js
front/src/components/Messages/Messages.style.js
front/src/components/globalComponents/Modal/Modal.js
front/src/components/globalComponents/Modal/Modal.style.js
front/src/components/globalComponents/Modal/ModalUsage.js

Feature modal

---

back/config/roomConfig.js
back/socket/Room.js
back/socket/game/message.js
front/src/components/GameInfo/GameInfo.js
front/src/components/GamePlay/CanvasSection/CanvasSection.js
front/src/components/GamePlay/GamePlay.js
front/src/logics/socketLogic/index.js

Feature end question

---

front/babel.config.js
front/package-lock.json
front/package.json
front/src/components/GamePlay/GamePlay.js
front/src/logics/socketLogic/index.js
front/test/logics/socketLogic/socket.test.js

프론트 테스트에 필요한 babel-jest 패키지 추가
소켓 테스트 틀 추가

add front test skeleton

---

front/src/components/FriendsSection/FriendsList/FriendComponents/FriendComponents.js

잘못된 Friend query import 수정

---

front/src/components/GamePlay/GameLoading/GameLoading.js
front/src/components/globalComponents/Alert/Alert.js
front/src/components/globalComponents/Loading/Loading.js

기존의 Alert와 Loading의 defaultProps가 작동하지 않는 에러 수정

Loading&Alert globalcomponent 수정

---

back/db/migrations/20191111065422-create-invitations.js
back/db/models/invitations.js
back/db/seeders/20191111071207-invitations.js
back/graphql/resolvers/invitation.js
back/graphql/typeDefs/invitation.js
front/src/components/FriendsSection/refactor/FriendList/FriendList.js
front/src/components/FriendsSection/refactor/FriendList/FriendList.style.js
front/src/components/NavigationBar/DefaultNavBtnContainer/Invitation/MessageList.js
front/src/components/Preparation/FriendList/Friend/Friend.js
front/src/components/Preparation/FriendList/FriendList.js
front/src/components/Preparation/FriendList/FriendList.style.js
front/src/components/Ranking/RankingAll/RankingAll.js
front/src/components/Ranking/RankingAll/RankingAll.style.js
front/src/components/Ranking/RankingFriends/RankingFriends.js
front/src/components/Ranking/RankingFriends/RankingFriends.style.js
front/src/components/Ranking/UserRankingList/UserRankingList.style.js
front/src/components/globalComponents/InfinityScroll/InfinityScroll.js
front/src/components/globalComponents/InfinityScroll/InfinityScroll.style.js
front/src/hooks/useCursorLazyQuery.js
front/src/hooks/useCursorQuery.js
front/src/logics/hooks/cursorQuery.js
front/src/pages/Main/Main.js
front/src/queries/invitation.js
front/src/themes/globalStyle.js

- 게임 준비 페이지에서 친구 초대 기능 구현
- 아직 소켓을 통한 알림 기능 구현x

친구 초대 기능 구현

---

back/graphql/resolvers/friend.js
back/graphql/typeDefs/friend.js
front/src/components/FriendsSection/refactor/FriendList/FriendList.js
front/src/components/FriendsSection/refactor/FriendList/FriendModal/FriendModal.js
front/src/components/FriendsSection/refactor/FriendList/modalReducer.js
front/src/pages/Main/Main.js
front/src/queries/friend.js

Feature design

---

back/config/timerConfig.js

Hotfix config

---

back/config/timerConfig.js
back/socket/Room.js
back/socket/game/index.js
back/util/makeReducerWithPromise.js
front/src/components/GamePlay/GamePlay.js
front/src/components/Timer/Timer.js
front/src/constant/timerConfig.js
front/src/logics/socketLogic/index.js

Hotfix disconnect

---

back/util/jwt/signJWT.js

Hotfix jwt

---

front/src/components/GamePlay/CanvasSection/WordPreview/WordPreview.js

fix(word preview): make don't open one letter word

---

front/src/components/VideoSection/VideoModal/VideoModal.js
front/src/components/globalComponents/Container/Background.style.js

style: modify Background, VideoModal

---

front/package-lock.json
front/package.json
front/src/Router.js
front/src/components/MyInfoSection/CurrentMyInfo/CurrentMyInfo.js
front/src/pages/MyPage.js
front/src/utils/catchmymind/auth.js

Hotfix not found and auth

---

front/src/components/GamePlay/CanvasSection/GameResult/GameResult.js
front/src/components/GamePlay/CanvasSection/QuestionResult/QuestionResult.js
front/src/utils/catchmymind/sorting.js

feat(scores): implement sorting scores at result modal

---

front/src/components/Preparation/GameSetting/CategorySetting.js
front/src/components/Preparation/GameSetting/GameSetting.js
front/src/components/Preparation/GameSetting/RoundSetting.js
front/src/components/Preparation/GameSetting/TimeSetting.js
front/src/components/globalComponents/Select/Select.js
front/src/pages/Main.js
front/src/pages/MyPage.js
front/src/pages/Setting.js
front/src/pages/Waiting.js

Feature refactor all

---

back/util/room/index.js

문제를 맞추고 나가면 미정답자가 있어도 게임이끝나는 버그
나갔을 때 인덱스 정리 안해줘서

Hotfix 게임중 문제를 맞추고 나가면 터지는 버그

---

back/util/room/index.js
front/src/components/GamePlay/CanvasSection/GameResult/GameResult.js
front/src/components/GamePlay/CanvasSection/QuestionResult/QuestionResult.js
front/src/components/GamePlay/Userlist/Userlist.js
front/src/utils/catchmymind/sorting.js

`nickname`대신 ``socketId`를 이용한 비교를 하기 위해, `[nickname, score]`의 배열에서 `{socketId, nickname, score}`의 배열로 수정함.

fix(scores): modify scores structure

---

front/src/components/GamePlay/Userlist/Userlist.js

삼항연산자를 쪼개서 undefined 관련 오류가 발생하지 않도록 수정함.

fix(scores): split ternary operator

---

back/socket/game/enterGame.js

Hotfix 비밀방 단어선택중일 때 난입시 에러

---

back/db/models/index.js
back/socket/online/checkFriendsOnline.js
back/util/room/index.js

- answererCount의 초기화가 IS_WAITING단계에서 안되었음

모두가 정답이어도 게임이 안끝나는 에러 수정
